# Generated by Django 3.1.6 on 2021-02-16 07:54

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': 'Coach', 'verbose_name_plural': 'Coachs'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='time_allocated',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'The minimum time allowed is 1 hour'), django.core.validators.MaxValueValidator(10, 'The maximum time allowed is 10 hours')], verbose_name='Temps Alloué'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[hub.models.is_Esprit_Email], verbose_name='Email'),
        ),
    ]
