# Generated by Django 3.1.6 on 2021-03-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20210216_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipinproject',
            name='time_allocated_by_member',
            field=models.IntegerField(default=0, verbose_name='Temps alloué par le membre'),
        ),
    ]
